/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

public class ReimbursementSystem {
    public static void main(String[] args) {
//        JavalinAppRoutes app = new JavalinAppRoutes();
//        app.start(7000);
    }


}
